#!/usr/bin/env perl
use warnings;
use strict;
my $HOME_DIR = $ENV{'HOME'};
my $CLONE_JHBUILD_COMMAND = 'git clone git://git.gnome.org/jhbuild';
while (1) {
    &menu;
}

sub print_reference_commands {
    print "jhbuild list xserver xf86-video-intel xf86-input-keyboard xf86-input-mouse\n";
    print 'jhbuild build xserver xf86-video-intel xf86-input-keyboard xf86-input-mouse > log.jhbuild 2>&1', "\n";
}

sub menu {
    print "\n\n\t(1) Install Jhbuild\n";
    print "\t(2) Install X.Org Modular Utility\n";
    print "\t(3) Print reference commands\n";
    print "\t(Q) Quit\n";
    print "\t\t? ";
    chomp (my $choice = <STDIN>);
    my $PROMPT = "\n\nPress any key to continue.";
    if ( $choice eq '1' ) {
	&install_jhbuild; print $PROMPT; my $input = <STDIN>;
    } elsif ( $choice eq '2' ) {
	&install_xorg_util_modular; print $PROMPT; my $input = <STDIN>;
    } elsif ( $choice eq '3' ) {
	&print_reference_commands; print $PROMPT; my $input = <STDIN>;
    } else {
	exit;
    }
}

sub install_jhbuild {
    my $SETUP_PATH_COMMAND = "echo 'export PATH=\$PATH:$HOME_DIR/.local/bin' >> $HOME_DIR/.bashrc";

    chdir $HOME_DIR;
    system $CLONE_JHBUILD_COMMAND;
    chdir "$HOME_DIR/jhbuild";
    print "$HOME_DIR/jhbuild ==>";
    system ("pwd");
    system( 'make -f Makefile.plain');
    system( 'make -f Makefile.plain install');
    system $SETUP_PATH_COMMAND;
    print "Please source $HOME_DIR/.bashrc\n";
}

sub install_xorg_util_modular {
    my $BASE_DIR = "$HOME_DIR/xorg/util";
    my $CLONE_XORG_MODULAR_COMMAND = "mkdir -p $HOME_DIR/xorg/util && git clone git://anongit.freedesktop.org/xorg/util/modular $HOME_DIR/xorg/util/modular";
    system $CLONE_XORG_MODULAR_COMMAND;
    use File::Copy;
    copy( "$BASE_DIR/modular/jhbuildrc", "$HOME_DIR/.jhbuildrc" ) or die "Copy failed: $!";
}
